"""Regenerate the navigation files that the agent must not hand-edit:

    wiki/<dir>/index.md   one line per page in that directory
    wiki/index.md         every page, grouped by directory, plus the special pages
    wiki/disputes.md      every non-empty "## Disputed" section in the wiki

Index lines come from page frontmatter (`title`, `summary`, `kind`), so the
index can never drift from the pages as long as this script runs after edits.

Usage:
    python build_index.py           # write the files
    python build_index.py --check   # exit 1 if any generated file is out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wikilib as W  # noqa: E402

GENERATED = "<!-- generated by build_index.py; do not edit by hand -->"


def page_line(page: W.Page) -> str:
    title = str(page.frontmatter.get("title") or page.name)
    summary = str(page.frontmatter.get("summary") or "").strip()
    marker = ""
    if page.kind == "synthesis":
        marker = " *(synthesis)*"
    conf = str(page.frontmatter.get("confidence") or "").strip().lower()
    if conf == "low":
        marker += " *(low confidence)*"
    link = f"[[{page.name}]]" if title == page.name else f"[[{page.name}|{title}]]"
    return f"- {link}{marker} — {summary}" if summary else f"- {link}{marker}"


def render(vault: Path, cfg: dict, pages: list[W.Page]) -> dict[str, str]:
    """Return {relpath: content} for every generated file."""
    wiki_dir = cfg["wiki_dir"].rstrip("/")
    out: dict[str, str] = {}
    by_dir: dict[str, list[W.Page]] = {d: [] for d in cfg["page_dirs"]}
    for page in pages:
        if W.is_special(page, cfg):
            continue
        parts = Path(page.relpath).parts
        if len(parts) >= 3 and parts[0] == wiki_dir and parts[1] in by_dir:
            by_dir[parts[1]].append(page)

    def sort_key(p: W.Page):
        return str(p.frontmatter.get("title") or p.name).lower()

    root_lines = [GENERATED, "# Index", "", "- [Overview](overview.md)", "- [Disputes](disputes.md)", "- [Log](log.md)", ""]
    for dirname, kind in cfg["page_dirs"].items():
        items = sorted(by_dir[dirname], key=sort_key)
        heading = dirname.capitalize()
        lines = [GENERATED, f"# {heading}", "", f"{len(items)} page(s) of kind `{kind}`.", ""]
        lines += [page_line(p) for p in items]
        out[f"{wiki_dir}/{dirname}/index.md"] = "\n".join(lines).rstrip() + "\n"
        root_lines.append(f"## {heading} ({len(items)})")
        root_lines.append("")
        root_lines.append(f"[Directory index]({dirname}/index.md)")
        root_lines.append("")
        root_lines += [page_line(p) for p in items]
        root_lines.append("")
    out[f"{wiki_dir}/index.md"] = "\n".join(root_lines).rstrip() + "\n"

    dispute_heading = cfg["dispute_section"]
    dlines = [GENERATED, "# Disputes", "", "Every page with a non-empty `## " + dispute_heading + "` section. Resolve by adding evidence, never by deleting a side.", ""]
    count = 0
    for page in sorted(pages, key=sort_key):
        text = page.sections.get(dispute_heading, "")
        if text and not W.section_is_empty(text):
            count += 1
            dlines.append(f"## [[{page.name}]]")
            dlines.append("")
            dlines.append(text)
            dlines.append("")
    if count == 0:
        dlines.append("_No open disputes._")
    out[f"{wiki_dir}/disputes.md"] = "\n".join(dlines).rstrip() + "\n"
    return out


def drift(vault: Path, rendered: dict[str, str]) -> list[str]:
    stale = []
    for relpath, content in rendered.items():
        path = vault / relpath
        if not path.is_file() or W.read_text(path) != content:
            stale.append(relpath)
    return stale


def main(argv: list[str] | None = None) -> int:
    W.configure_stdout()
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report out-of-date files, write nothing")
    args = ap.parse_args(argv)

    vault = W.find_vault()
    cfg = W.load_config(vault)
    pages = W.iter_wiki_pages(vault, cfg)
    rendered = render(vault, cfg, pages)
    stale = drift(vault, rendered)
    if args.check:
        for relpath in stale:
            print(f"out of date: {relpath}")
        print("indexes up to date" if not stale else f"{len(stale)} file(s) need rebuilding")
        return 1 if stale else 0
    for relpath, content in rendered.items():
        W.write_text(vault / relpath, content)
    print(f"wrote {len(rendered)} file(s); {len(stale)} changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
